name: zaarvis_ai
description: Voice-enabled AI assistant
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.22.2"

dependencies:
  flutter:
    sdk: flutter
  characters: "1.4.0"
  material_color_utilities: "0.11.1"
  meta: "1.16.0"
  vector_math: "2.1.4"
  flutter_tts: ^3.6.3
  speech_to_text: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
