name: zaarvis_ai
description: A new Flutter project for Zaarvis AI assistant.

publish_to: 'none' # Remove this line if publishing to pub.dev

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  speech_to_text: ^6.5.0
  flutter_tts: ^3.8.4
  http: ^0.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true